# -*- coding: utf-8 -*-
"""02_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Sourav61/MLnow_2.0/blob/main/02_EDA.ipynb
"""

from google.colab import drive
drive.mount('/content/drive')

cd'/content/drive/MyDrive/student-mat.csv'

import pandas as pd #working with csv or excel files
import numpy as np #working with numbers/ arrays/ tensors
import tensorflow as tf #framework
from tensorflow import keras #API / library 
import os #using os commands between the python language

df = pd.read_csv("student-mat.csv",sep=';')
df

df.head(10)

df.tail(10)

print(f'school: {df.school.unique()}')
print(f'sex: {df.sex.unique()}')
print(f'address: {df.address.unique()}')
print(f'Mjob: {df.Mjob.unique()}')
print(f'Fjob: {df.Fjob.unique()}')
print(f'higher: {df.higher.unique()}')

